export { default as About } from './About'
export { default as Hero } from './Hero'
export { default as Product } from './Product'
export { default as Reviews} from './Reviews'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'